# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gstReg', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('state', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('payType', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('invoiceNumber', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('subTotal', models.FloatField(default=0.0)),
                ('disc', models.FloatField(default=0.0)),
                ('taxable', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('roundOff', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('gst', models.FloatField(default=0.0)),
                ('netPrice', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('barCode', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('hsn', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('mrp', models.FloatField(default=0.0)),
                ('itemDisc', models.FloatField(default=0.0)),
                ('billDisc', models.FloatField(default=0.0)),
                ('salesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sales')),
            ],
        ),
    ]
