# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190930_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='name',
            new_name='accHolderName',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bankName',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
