# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191010_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
