# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
