# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191013_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CompanyProfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='wareHouse_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.WareHouse'),
        ),
    ]
