# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191016_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
