# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191022_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
