# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191030_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hsn',
        ),
        migrations.AlterField(
            model_name='category',
            name='hsnID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Hsn'),
        ),
    ]
