# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-11-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_sales_salesproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
