# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-11-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20191113_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
