# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-11-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20191116_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='buyersOrderNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='chequeDetail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='deliveryNote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='destination',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='dispatchDocumentNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='dispatchNoteDate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='dispatchThrough',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='otherCharges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales',
            name='otherReference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='supplierReference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
