# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-11-25 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20191123_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='addedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
