# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-11-27 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0031_printersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrinterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printerID', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.PrinterSetting')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
