# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-18 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_userprintersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseType',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
