# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-07-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200531_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='certificateDetail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sales',
            name='isCertified',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
